// Refresh the self-hosted web fonts in apps/web/public/fonts/.
//
// The pages used to pull Inter and JetBrains Mono straight from Google, which
// meant every visitor's IP address went to Google before the page had rendered
// - not a good default for a messenger built around not being observed. It
// also forced the CSP to allow a third-party style and font origin.
//
// Run this only when the font list or the weights change:
//   node scripts/fetch-fonts.js
// It rewrites public/fonts/*.woff2 and public/fonts.css. Both are committed,
// so a normal build and a normal deploy need no network access.
import fs from "node:fs";
import path from "node:path";

const FAMILIES = "family=JetBrains+Mono:wght@400;500;700&family=Inter:wght@400;500;600;700";
// Latin covers German and English including umlauts; latin-ext adds the rest
// of central/eastern Europe. Cyrillic, Greek and Vietnamese are left out on
// purpose - they would roughly triple the download for text that falls back to
// a system font perfectly well.
const SUBSETS = new Set(["latin", "latin-ext"]);
// woff2 is only offered to a browser-shaped user agent.
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const OUT_DIR = "apps/web/public/fonts";
const OUT_CSS = "apps/web/public/fonts.css";

const res = await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, { headers: { "user-agent": UA } });
if (!res.ok) throw new Error(`google fonts css -> ${res.status}`);
const css = await res.text();

const faces = [];
for (const m of css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g)) {
  const [, subset, body] = m;
  if (!SUBSETS.has(subset)) continue;
  const pick = (re) => (re.exec(body) || [])[1];
  const family = pick(/font-family:\s*['"]([^'"]+)['"]/);
  const weight = pick(/font-weight:\s*(\d+)/);
  const style = pick(/font-style:\s*(\w+)/);
  const url = pick(/url\(([^)]+)\)/);
  const range = pick(/unicode-range:\s*([^;]+)/);
  if (!family || !weight || !url) throw new Error("could not parse a @font-face block");
  faces.push({ family, weight, style, url, range, file: `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${subset}.woff2` });
}
if (!faces.length) throw new Error("no matching @font-face blocks - did the css format change?");

fs.mkdirSync(OUT_DIR, { recursive: true });
for (const f of faces) {
  const r = await fetch(f.url);
  if (!r.ok) throw new Error(`${f.file} -> ${r.status}`);
  fs.writeFileSync(path.join(OUT_DIR, f.file), Buffer.from(await r.arrayBuffer()));
}

const header = `/* Self-hosted copies of Inter and JetBrains Mono.
 *
 * These used to come from fonts.googleapis.com, which handed Google the IP
 * address of every visitor - a poor look for a messenger whose entire point is
 * that nobody gets to watch who is talking. Serving them from here also lets
 * the CSP drop 'unsafe-inline' for styles and any third-party font origin.
 *
 * Generated by scripts/fetch-fonts.js - edit that, not this.
 */
`;
const blocks = faces.map((f) => `@font-face {
  font-family: "${f.family}";
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url("/fonts/${f.file}") format("woff2");
  unicode-range: ${f.range};
}`);
fs.writeFileSync(OUT_CSS, header + blocks.join("\n") + "\n");
console.log(`${faces.length} font files -> ${OUT_DIR}, stylesheet -> ${OUT_CSS}`);
